name: beak-ta3
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.15
  - numpy==1.24.3
  - pandas==2.1.0
  - scikit-learn==1.3.0
  - scipy==1.11.2
  - statsmodels==0.14.0
  - matplotlib==3.7.2
  - matplotlib-scalebar==0.8.1
  - seaborn==0.12.2
  - plotly==5.16.1
  - gdal==3.7.1
  - rasterio==1.3.8
  - geopandas==0.13.2
  - beartype==0.15.0
  - tqdm==4.65.0
  - shapely==2.0.2
  - imbalanced-learn==0.11.0
  - pip:
    - ipykernel==6.26.0
    - notebook==7.0.3
    - tensorflow==2.13.1
    - tensorflow_probability==0.21.0
    - somoclu==1.7.6
    - pip-licenses==4.3.3
    - mkdocs==1.5.3
    - mkdocstrings[python]==0.24
    - mkdocs-material==9.4.14
    - autoflake==2.2.1
    - pyarrow==14.0.1
  
