name: beak-ta3
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.15
  - numpy==1.24.3
  - rasterio==1.3.8
  - pandas==2.1.0
  - geopandas >=0.12.2,<1.0.0
  - fiona >=1.8.22,<2.0.0
  - gdal >=3.0.2,<4.0.0
  - geos >=3.8.0,<4.0.0
  - shapely==2.0.2
  - scikit-learn==1.3.0
  - scipy==1.11.2
  - statsmodels==0.14.0
  - imbalanced-learn==0.11.0
  - matplotlib==3.7.2
  - matplotlib-scalebar==0.8.1
  - seaborn==0.12.2
  - plotly==5.16.1
  - beartype==0.15.0
  - tqdm==4.65.0
  - rtree >= 1.0.1