name: beak-ta3
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.15
  - numpy==1.24.3
  - pandas==2.1.0
  - scikit-learn==1.3.0
  - scipy==1.11.2
  - statsmodels==0.14.0
  - matplotlib==3.7.2
  - matplotlib-scalebar==0.8.1
  - seaborn==0.12.2
  - plotly==5.16.1
  - gdal==3.7.1
  - rasterio==1.3.8
  - geopandas==0.13.2
  - beartype==0.15.0
  - tqdm==4.65.0
  - shapely==2.0.2
