channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.4.0
  - affine=2.4.0
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - alsa-lib=1.2.9
  - ansi2html=1.8.0
  - arviz=0.16.1
  - asttokens=2.2.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beartype=0.15.0
  - black=23.7.0
  - blinker=1.6.2
  - blosc=1.21.5
  - boost-cpp=1.78.0
  - branca=0.6.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.1
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=4.3.0
  - charset-normalizer=3.2.0
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.4
  - cons=0.4.6
  - contourpy=1.1.0
  - cryptography=41.0.3
  - cycler=0.11.0
  - dash=2.13.0
  - dbus=1.13.6
  - debugpy=1.6.8
  - decorator=5.1.1
  - dm-tree=0.1.8
  - etuples=0.3.9
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - expat=2.5.0
  - fastprogress=1.0.3
  - filelock=3.12.3
  - fiona=1.9.4
  - flake8=6.1.0
  - flask=2.3.3
  - flatbuffers=23.5.26
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.1
  - freetype=2.12.1
  - freexl=1.0.6
  - frozenlist=1.4.0
  - gast=0.4.0
  - gdal=3.7.1
  - geopandas=0.13.2
  - geopandas-base=0.13.2
  - geos=3.12.0
  - geotiff=1.7.1
  - gettext=0.21.1
  - gevent=22.10.2
  - giflib=5.2.1
  - glib=2.76.4
  - glib-tools=2.76.4
  - google-auth=2.22.0
  - google-auth-oauthlib=1.0.0
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - greenlet=2.0.2
  - grpcio=1.54.3
  - gst-plugins-base=1.22.5
  - gstreamer=1.22.5
  - h5netcdf=1.2.0
  - h5py=3.9.0
  - harfbuzz=7.3.0
  - hdf4=4.2.15
  - hdf5=1.14.2
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib-resources=6.0.1
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - iniconfig=2.0.0
  - ipykernel=6.25.1
  - ipython=8.15.0
  - isort=5.12.0
  - itsdangerous=2.1.2
  - jax=0.4.14
  - jaxlib=0.4.14
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - json-c=0.17
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - kealib=1.5.1
  - keras=2.12.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.0.6
  - libarchive=3.6.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=8.2.1
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgdal=3.7.1
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libgomp=13.1.0
  - libgpg-error=1.47
  - libgrpc=1.54.3
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnetcdf=4.9.2
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.4
  - libprotobuf=3.21.12
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=254
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libuv=1.46.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxkbcommon=1.5.0
  - libxml2=2.11.5
  - libzip=1.10.1
  - libzlib=1.2.13
  - logical-unification=0.4.6
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.5.0
  - markdown=3.4.4
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - matplotlib-scalebar=0.8.1
  - mccabe=0.7.0
  - minikanren=1.0.3
  - ml_dtypes=0.2.0
  - mpg123=1.31.3
  - multidict=6.0.4
  - multipledispatch=0.6.0
  - munch=4.0.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nspr=4.35
  - nss=3.92
  - numpy=1.25.2
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.1.2
  - opt_einsum=3.3.0
  - packaging=23.1
  - pandas=2.1.0
  - parso=0.8.3
  - pathspec=0.11.2
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.0
  - pip=23.2.1
  - pixman=0.40.0
  - platformdirs=3.5.1
  - plotly=5.16.1
  - pluggy=1.3.0
  - ply=3.11
  - pooch=1.7.0
  - poppler=23.08.0
  - poppler-data=0.4.12
  - postgresql=15.4
  - proj=9.2.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - protobuf=4.21.12
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.11.0
  - pycparser=2.21
  - pyflakes=3.1.0
  - pygments=2.16.1
  - pyjwt=2.8.0
  - pymc=5.6.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyproj=3.6.0
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - pytensor=2.12.3
  - pytest=7.4.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-flatbuffers=23.5.26
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3
  - pyu2f=0.1.5
  - pyzmq=25.1.1
  - qt-main=5.15.8
  - rasterio=1.3.8
  - re2=2023.03.02
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - retrying=1.3.3
  - rsa=4.9
  - rtree=1.0.1
  - scikit-learn=1.3.0
  - scipy=1.11.2
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=68.1.2
  - shapely=2.0.1
  - sip=6.7.11
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - somoclu=1.7.6
  - sqlite=3.43.0
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - tenacity=8.2.3
  - tensorboard=2.12.3
  - tensorboard-data-server=0.7.0
  - tensorflow=2.12.1
  - tensorflow-base=2.12.1
  - tensorflow-estimator=2.12.1
  - tensorflow-probability=0.20.0
  - termcolor=2.3.0
  - threadpoolctl=3.2.0
  - tiledb=2.16.3
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.3
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzcode=2023c
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - werkzeug=2.3.7
  - wheel=0.41.2
  - wrapt=1.15.0
  - xarray=2023.8.0
  - xarray-einstats=0.6.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.4
  - xkeyboard-config=2.39
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2023.7.0
  - xz=5.2.6
  - yarl=1.9.2
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zope.event=5.0
  - zope.interface=6.0
  - zstd=1.5.5
