"""
This file contains the models used for the magmatic cobalt-nickel experiment.
The BISON model is used as a geophysical baseline model and is the same as the pre-hack FOX model.
"""

models = {
    "BASELINE_BISON": {
        # Geophysics: Seismic
        "LAB": True,
        "LAB_HGM": True,
        "LAB_Worms_Proximity": True,
        "Moho": True,
        # Geophysics: Gravity
        "SatelliteGravity_ShapeIndex": True,
        "Gravity": True,
        "Gravity_HGM": True,
        "ShallowGravitySources_Worms_Proximity": True,
        "Gravity_Up30km": True,
        "Gravity_Up30km_HGM": True,
        "DeepGravitySources_Worms_Proximity": True,
        "IsostaticGravity": True,
        "IsostaticGravity_HGM": True,
        "IsostaticGravity_Worms_Proximity": True,
        # Geophysics: Magnetic
        "Mag_RTP": True,
        "Mag_RTP_HGM": True,
        "ShallowMagSources_Worms_Proximity": True,
        "Mag_RTP_DeepSources": True,
        "Mag_RTP_HGM_DeepSources": True,
        "DeepMagSources_Worms_Proximity": True,
        # Geophysics: Magnetotelluric
        "CONUS_MT2023_9km": True,
        "CONUS_MT2023_15km": True,
        "CONUS_MT2023_30km": True,
        "CONUS_MT2023_48km": True,
        "CONUS_MT2023_92km": True,
        # Geophysics: Radiometrics
        "NAMrad_K": True,
        "NAMrad_Th": True,
        "NAMrad_U": True,
    },
    "MAFIC_MOOSE": {
        # Geophysics: Seismic
        "LAB": True,
        "LAB_HGM": True,
        "LAB_Worms_Proximity": True,
        "Moho": True,
        # Geophysics: Gravity
        "SatelliteGravity_ShapeIndex": True,
        "Gravity": True,
        "Gravity_HGM": True,
        "ShallowGravitySources_Worms_Proximity": True,
        "Gravity_Up30km": True,
        "Gravity_Up30km_HGM": True,
        "DeepGravitySources_Worms_Proximity": True,
        "IsostaticGravity": True,
        "IsostaticGravity_HGM": True,
        "IsostaticGravity_Worms_Proximity": True,
        # Geophysics: Magnetic
        "Mag_RTP": True,
        "Mag_RTP_HGM": True,
        "ShallowMagSources_Worms_Proximity": True,
        "Mag_RTP_DeepSources": True,
        "Mag_RTP_HGM_DeepSources": True,
        "DeepMagSources_Worms_Proximity": True,
        # Geophysics: Magnetotelluric
        "CONUS_MT2023_9km": True,
        "CONUS_MT2023_15km": True,
        "CONUS_MT2023_30km": True,
        "CONUS_MT2023_48km": True,
        "CONUS_MT2023_92km": True,
        # Geophysics: Radiometrics
        "NAMrad_K": True,
        "NAMrad_Th": True,
        "NAMrad_U": True,
        # Geology
        "mafic_macrostrat": True,
    },
    "CAMEL_CASE": {
        # Geophysics: Seismic
        "LAB": True,
        "LAB_HGM": True,
        "LAB_Worms_Proximity": True,
        "Moho": True,
        # Geophysics: Gravity
        "SatelliteGravity_ShapeIndex": True,
        "Gravity": False,
        "Gravity_HGM": False,
        "ShallowGravitySources_Worms_Proximity": True,
        "Gravity_Up30km": True,
        "Gravity_Up30km_HGM": True,
        "DeepGravitySources_Worms_Proximity": True,
        "IsostaticGravity": False,
        "IsostaticGravity_HGM": True,
        "IsostaticGravity_Worms_Proximity": True,
        "CEUS_GRAV_RI_HD_1VD_CEUSSSC_R0": True,
        "CEUS_GRAV_RI_HD_CEUSSSC_R0": True,
        "CEUS_GRAV_Isostatic_CEUSSSC_R0": True,
        "CEUS_GRAV_RI_CEUSSSC_R0": True,
        "CEUS_GRAV_RI_1VD_CEUSSSC_R0": True,
        # Geophysics: Magnetic
        "Mag_RTP": True,
        "Mag_RTP_HGM": True,
        "ShallowMagSources_Worms_Proximity": True,
        "Mag_RTP_DeepSources": True,
        "Mag_RTP_HGM_DeepSources": True,
        "DeepMagSources_Worms_Proximity": True,
        "CEUS_MAG_TMAG_AAS_CEUSSSC_R0": True,
        "CEUS_MAG_DRTP_TDR_CEUSSSC_R0": True,
        "CEUS_MAG_DRTP_HD_TDR_CEUSSSC_R0": True,
        "CEUS_MAG_DRTP_CEUSSSC_R0": True,
        # Geophysics: Magnetotelluric
        "CONUS_MT2023_9km": True,
        "CONUS_MT2023_15km": True,
        "CONUS_MT2023_30km": True,
        "CONUS_MT2023_48km": True,
        "CONUS_MT2023_92km": True,
        # Geophysics: Radiometrics
        "NAMrad_K": True,
        "NAMrad_Th": True,
        "NAMrad_U": True,
        # Geology
        "mafic_macrostrat": True,
    },
    "COSMIC_CHAMELEON": {
        # Geophysics: Seismic
        "LAB": True,
        "LAB_HGM": True,
        "LAB_Worms_Proximity": True,
        "Moho": True,
        # Geophysics: Gravity
        "SatelliteGravity_ShapeIndex": True,
        "Gravity": True,
        "Gravity_HGM": True,
        "ShallowGravitySources_Worms_Proximity": True,
        "Gravity_Up30km": True,
        "Gravity_Up30km_HGM": True,
        "DeepGravitySources_Worms_Proximity": True,
        "IsostaticGravity": False,
        "IsostaticGravity_HGM": True,
        "IsostaticGravity_Worms_Proximity": True,
        "CEUS_GRAV_RI_HD_1VD_CEUSSSC_R0": True,
        "CEUS_GRAV_RI_HD_CEUSSSC_R0": True,
        "CEUS_GRAV_Isostatic_CEUSSSC_R0": True,
        "CEUS_GRAV_RI_CEUSSSC_R0": True,
        "CEUS_GRAV_RI_1VD_CEUSSSC_R0": True,
        # Geophysics: Magnetic
        "Mag_RTP": True,
        "Mag_RTP_HGM": True,
        "ShallowMagSources_Worms_Proximity": True,
        "Mag_RTP_DeepSources": True,
        "Mag_RTP_HGM_DeepSources": True,
        "DeepMagSources_Worms_Proximity": True,
        "CEUS_MAG_TMAG_AAS_CEUSSSC_R0": True,
        "CEUS_MAG_DRTP_TDR_CEUSSSC_R0": True,
        "CEUS_MAG_DRTP_HD_TDR_CEUSSSC_R0": True,
        "CEUS_MAG_DRTP_CEUSSSC_R0": True,
        # Geophysics: Magnetotelluric
        "CONUS_MT2023_9km": True,
        "CONUS_MT2023_15km": True,
        "CONUS_MT2023_30km": True,
        "CONUS_MT2023_48km": True,
        "CONUS_MT2023_92km": True,
        # Geophysics: Radiometrics
        "NAMrad_K": True,
        "NAMrad_Th": True,
        "NAMrad_U": True,
        # Geology
        "mafic_macrostrat": True,
    },
    "CHARCOAL_CROW": {
        # Geophysics: Seismic
        "LAB": True,
        "LAB_HGM": True,
        "LAB_Worms_Proximity": True,
        "Moho": True,
        # Geophysics: Gravity
        "SatelliteGravity_ShapeIndex": True,
        "Gravity": False,
        "Gravity_HGM": False,
        "ShallowGravitySources_Worms_Proximity": True,
        "Gravity_Up30km": True,
        "Gravity_Up30km_HGM": True,
        "DeepGravitySources_Worms_Proximity": True,
        "IsostaticGravity": False,
        "IsostaticGravity_HGM": True,
        "IsostaticGravity_Worms_Proximity": True,
        "CEUS_GRAV_RI_HD_1VD_CEUSSSC_R0": True,
        "CEUS_GRAV_RI_HD_CEUSSSC_R0": True,
        "CEUS_GRAV_Isostatic_CEUSSSC_R0": True,
        "CEUS_GRAV_RI_CEUSSSC_R0": True,
        "CEUS_GRAV_RI_1VD_CEUSSSC_R0": True,
        # Geophysics: Magnetic
        "Mag_RTP": False,
        "Mag_RTP_HGM": False,
        "ShallowMagSources_Worms_Proximity": True,
        "Mag_RTP_DeepSources": True,
        "Mag_RTP_HGM_DeepSources": True,
        "DeepMagSources_Worms_Proximity": True,
        "CEUS_MAG_TMAG_AAS_CEUSSSC_R0": True,
        "CEUS_MAG_DRTP_TDR_CEUSSSC_R0": True,
        "CEUS_MAG_DRTP_HD_TDR_CEUSSSC_R0": True,
        "CEUS_MAG_DRTP_CEUSSSC_R0": True,
        # Geophysics: Magnetotelluric
        "CONUS_MT2023_9km": True,
        "CONUS_MT2023_15km": True,
        "CONUS_MT2023_30km": True,
        "CONUS_MT2023_48km": True,
        "CONUS_MT2023_92km": True,
        # Geophysics: Radiometrics
        "NAMrad_K": True,
        "NAMrad_Th": True,
        "NAMrad_U": True,
        # Geology
        "mafic_macrostrat": True,
    },
    "PRE_HACK_FEATURE_FOX": {
        # Geophysics: Seismic
        "LAB": True,
        "LAB_HGM": True,
        "LAB_Worms_Proximity": True,
        "Moho": True,
        # Geophysics: Gravity
        "SatelliteGravity_ShapeIndex": True,
        "Gravity": True,
        "Gravity_HGM": True,
        "ShallowGravitySources_Worms_Proximity": True,
        "Gravity_Up30km": True,
        "Gravity_Up30km_HGM": True,
        "DeepGravitySources_Worms_Proximity": True,
        "IsostaticGravity": True,
        "IsostaticGravity_HGM": True,
        "IsostaticGravity_Worms_Proximity": True,
        # Geophysics: Magnetic
        "Mag_RTP": True,
        "Mag_RTP_HGM": True,
        "ShallowMagSources_Worms_Proximity": True,
        "Mag_RTP_DeepSources": True,
        "Mag_RTP_HGM_DeepSources": True,
        "DeepMagSources_Worms_Proximity": True,
        # Geophysics: Magnetotelluric
        "CONUS_MT2023_9km": True,
        "CONUS_MT2023_15km": True,
        "CONUS_MT2023_30km": True,
        "CONUS_MT2023_48km": True,
        "CONUS_MT2023_92km": True,
        # Geophysics: Radiometrics
        "NAMrad_K": True,
        "NAMrad_Th": True,
        "NAMrad_U": True,
    },
}
