"""
This file contains the models used for the magmatic nico experiment.
The BISON model is used as a geophysical baseline model for deeper sources (even shallow, but no surface data).
The JELLYFISH model is most comparable to the google sheet model configuration, but does not include high-res data.
"""
regional_scale_great_basin = {
    "BASELINE_BISON": {
        "Geophysics_Gravity_Bouguer_HGM": True,
        "Geophysics_Gravity_Bouguer_Up30km": True,
        "Geophysics_Gravity_Bouguer_Up30km_HGM": True,
        "Geophysics_Gravity_Isostatic": True,
        "Geophysics_Gravity_Isostatic_HGM": True,
        "Geophysics_MT2023_15km": True,
        "Geophysics_MT2023_9km": True,
        "Geophysics_Radiometric_Potassium": False,
        "Geophysics_Radiometric_Thorium": False,
        "Geophysics_Radiometric_Uranium": False,
        "Geophysics_LAB": True,
        "Geophysics_LAB_HGM": True,
        "Geophysics_Moho": True,
        "Geophysics_Mag_RTP": True,
        "Geophysics_Mag_RTP_HGM": True,
    },
    "JITTER_JELLYFISH": {
        "Geophysics_Gravity_Bouguer_HGM": True,
        "Geophysics_Gravity_Bouguer_Up30km": True,
        "Geophysics_Gravity_Bouguer_Up30km_HGM": True,
        "Geophysics_Gravity_Isostatic": True,
        "Geophysics_Gravity_Isostatic_HGM": True,
        "Geophysics_MT2023_15km": True,
        "Geophysics_MT2023_9km": True,
        "Geophysics_Radiometric_Potassium": True,
        "Geophysics_Radiometric_Thorium": True,
        "Geophysics_Radiometric_Uranium": True,
        "Geophysics_LAB": True,
        "Geophysics_LAB_HGM": True,
        "Geophysics_Moho": True,
        "Geophysics_Mag_RTP": True,
        "Geophysics_Mag_RTP_HGM": True,
        "sgmc_geology_min_ma": True,
        "sgmc_geology_max_ma": True,
        "sgmc_preproc_v1.tungsten_skarn_bge_rock_types": True,
        "SGMC_Geology_carbonate_proximity": True,
        "SGMC_Geology_granodiorite_proximity": True,
        "Carbonates": True,
        "Epidote-chlorite": True,
        "Muscovite": True,
        "Muscovite_sil_rich": True,
        "Hydro_silica": True,
        "Kaol_Alun": True,
        "Kaol_Alun_Sil": True,
    },
    "PIXEL_PEEPER": {
        "Geophysics_Gravity_Bouguer_HGM": True,
        "Geophysics_Gravity_Bouguer_Up30km": True,
        "Geophysics_Gravity_Bouguer_Up30km_HGM": True,
        "Geophysics_Gravity_Isostatic": True,
        "Geophysics_Gravity_Isostatic_HGM": True,
        "Geophysics_MT2023_15km": True,
        "Geophysics_MT2023_9km": True,
        "Geophysics_LAB": True,
        "Geophysics_LAB_HGM": True,
        "Geophysics_Moho": True,
        "Geophysics_Mag_RTP": False,
        "Geophysics_Mag_RTP_HGM": True,
        "22103_rtp_a2": True,
        "22103_tmi_a2": True,
        "22103_tmi_vg_a2": True,
        "22103_k_a2": True,
        "22103_th_a2": True,
        "22103_u_a2": True,
        "sgmc_geology_min_ma": True,
        "sgmc_geology_max_ma": True,
        "sgmc_preproc_v1.tungsten_skarn_bge_rock_types": True,
        "SGMC_Geology_carbonate_proximity": True,
        "SGMC_Geology_granodiorite_proximity": True,
        "Carbonates": True,
        "Epidote-chlorite": True,
        "Muscovite": True,
        "Muscovite_sil_rich": True,
        "Hydro_silica": True,
        "Kaol_Alun": True,
        "Kaol_Alun_Sil": True,
    }
}

