name: beak-ta3                                        # Compose stack name

services:
  dev:
    stdin_open: true                                  # Run interactively
    tty: true
    build:
      context: ../../..                               # Build from root directory
      dockerfile: setup/docker/conda/Dockerfile
    image: beak-ta3:dev                               # Override default image naming
    ports:
      - 8888:8888                                     # Ports for jupyter
    volumes:
      - ../../../:/beak-ta3/                          # Mount the repo
    container_name: beak-ta3